### ISSUE TITLE
Add tokens for animation durations

### ISSUE THREAD

**Issue by eltongarbin** [ocean-ds/ocean-tokens#168]
**Is your feature request related to a problem? Please describe.**
In different places, the same animation has a different duration because we don't have a common pattern between platforms.

**Describe the solution you'd like**
I think we could create tokens that represent a variety of time duration to be used in animations.

**Describe alternatives you've considered**
- https://github.com/salesforce-ux/design-system/blob/master/design-tokens/aliases/duration.yml
- https://github.com/Shopify/polaris-tokens/blob/main/dist/duration.json

**Comment by julianasouza-s** [comment]
Closing this issue for now. Will get back to it in the future.
