### ISSUE TITLE
Change color token name

### ISSUE THREAD

**Issue by julianasouza-s** [ocean-ds/ocean-tokens#250]
Change colors name from Status Neutral to **Status Warning.**
<s>$color-status-neutral-pure</s> -> $color-status-warning-pure
<s>$color-status-neutral-up</s> -> $color-status-warning-up
<s>$color-status-neutral-down</s> -> $color-status-warning-down
<s>$color-status-neutral-deep</s> -> $color-status-warning-deep

**Comment by joaopedrorc** [comment]
Done!
